spring.profiles.active: dev

logging.config: classpath:log4j2-prod.xml

server:
  port: 47789
  servlet:
    context-path: /meter-server
  undertow:
    accesslog:
      enabled: false
      rotate: true
      dir: /opt/smartwater/meter-server/undertow
    io-threads: 2
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true

druid:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 30000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  datasource-meter:
    name: datasource-meter
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application:
    name: meter-server

param.config.version: 2.5
param.config.findPageSize: 5000
param.config.times: 24
param.config.expire: 86400
param.config.timeOut: 50000

mybatis.configLocation: classpath:mybatis-config.xml

param:
  config:
    timer:
      Test: 60
      CheckDeviceValveCommands: 3600
      CheckDeviceValveCommandStatuss: 3600
      CheckOwners: 1800
      RefreshDeviceUplinks: 1800

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 30
    registerWithEureka: true
    fetchRegistry: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  eureka:
    enabled: true
  ReadTimeout: 1200000
  ConnectTimeout: 1200000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000


netty:
  timeout: 900
  #不能用localhost,否则启动报异常:Unresolved address
  #tcp监听的端口
  tcp:
    port: 34567
  # bossGroup的线程数
  boss:
    thread:
      count: 16
  # worker的线程数
  worker:
    thread:
      count: 16
  #是否使用长连接
  socket:
    keepalive:  true
    backlog: 1024