logging:
  config: classpath:log4j2-dev.xml

druid:
  datasource:
    url: jdbc:mysql://222.20.83.207:3306/water?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  dbbackup:
    host: 222.20.83.207
    port: 3306
    #todo 我们应当备份到哪里BY
    dbname: water_2.6
    mysqldump: d:\\mysql-5.7.22-winx64\\bin\\mysqldump
    outputpath: D:\\home\\meter\\

redis:
  cache:
    database: 14
    host: 222.20.83.207
    password:
    port: 6379

oss:
  AccessKeyId:
  AccessKeySecret:
  endpoint:
  bucketName:
  fileDir: water-cas/

mybatis:
  mapperLocations: classpath*:com/dotop/smartwater/project/module/dao/**/*.xml
  configLocation: classpath:mybatis-config-dev.xml

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring.servlet.multipart.location: D:\\Java\\upload_temp\\

ajaxUpload:
  tempUrl: D:\\Java\\upload_temp\\
  MEMORY_THRESHOLD: 2097152
  MAX_FILE_SIZE: 2097152
  MAX_REQUEST_SIZE: 2097152

param:
  revenue:
    excelTempUrl: d:/logs/water/temp
  config:
    version: 2.5
    userinvalidtime: 7
    serverhost: #下发指令地址
    weixindebug: true
    authserverurl: http://localhost:39000/water-cas
    paycallbackurl: http://localhost:38888/water-server/payment/callback