druid:
  datasource:
    url: jdbc:mysql://222.20.83.207:3306/pipe?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
redis:
  cache:
    database: 5
    host: 222.20.83.207
    password:
    port: 6379
    
cas.auth.path: http://localhost:39999/water-cas

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

dispatch-server.ribbon.listOfServers: http://localhost:8080

spring.servlet.multipart.location: D:\\Java\\upload_temp\\
upload.base.path: D:\\Java\\upload\\
download.error.txt.path: D:\\java\\upload\\

mybatis:
  configLocation: classpath:mybatis-config.xml
