druid:
  datasource-meter:
    name: datasource-meter
    url: jdbc:mysql://222.20.83.207:3306/water?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456

redis:
  cache:
    database: 30
    host: 222.20.83.207
    password:
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

combine.file.path: /opt/smartwater/meter-server/file/combine/App.bin