spring.profiles.active: dev

logging.config: classpath:log4j2-prod.xml

server:
  port: 35559
  servlet:
    context-path: /meterread-client

druid:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 30000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  datasource-third:
    name: datasource-third
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

spring:
  application:
    name: meterread-client

param.config.version: 2.5
param.config.findPageSize: 100
param.config.times: 24
param.config.expire: 86400
param.config.timeOut: 60000

mybatis.configLocation: classpath:mybatis-config.xml

#param:
#  config:
#    timer:
#      Test: 60
#      CheckDeviceValveCommands: 21600
#      CheckDeviceValveCommandStatuss: 21600
#      CheckOwners: 43200
#      RefreshDeviceUplinks: 43200
