logging:
  config: classpath:log4j2-dev.xml

wechat:
  notify_url: http://admin.zhdt-tech.com/water-pay/callback/weChatPay

druid:
  datasource:
    url: jdbc:mysql://rm-wz91y5du7xqr0aot9.mysql.rds.aliyuncs.com:3306/water?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: water
    password: 02f471eFBb6

redis:
  cache:
    database: 1
    host: r-wz9ewh0547c5u7eugl.redis.rds.aliyuncs.com
    password: 6DCC6abA6CcE7
    port: 6379

oss:
  AccessKeyId:
  AccessKeySecret:
  endpoint:
  bucketName:
  fileDir: water-cas/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

param:
  config:
    version: 2.5
    userinvalidtime: 7
    serverhost: #下发指令地址
    weixindebug: true
    authserverurl: http://localhost/water-cas